### PR TITLE
Refactor to use one request object

### PR DESCRIPTION
**Pull request by lanwin**
This approach is simple and allows batching of changes.

Currently work in progress.

### CODE REVIEW

**Comment by lanwin** [comment]
@atanasenko since it seems you have experience in c++ programming. What do you think about that approach? 

A problem is that optional type. std::optional is not supported yet since esphome uses c++ 14. And I can not use the esphome::optional since this one is not available for my test script. That should run on my local window machine where I have the esphome source not available.

**Comment by atanasenko** [comment]
But I was looking at the transport code and I think requests could be batched, but on a lower, packet level.
For example, when changes are requested, they get appended to an existing queued packet (as long as packet type is the same) instead of sending a separate packet. Then the sending loop will try to send a single packet at the front of the queue and will only remove it once it's acked.

**Comment by lanwin** [comment]
> I'm a java dev mostly, and have very limited experience with cpp, unfortunately. Most of what I did in those prs was copy-paste :)

Well the you are pretty fast in copy and paste :D

**Comment by lanwin** [comment]
Yes that is true. But my goal with the request object is also to reduce the api.

**Pull request merged**
