### PR TITLE
add Water Heater Power

### PR DESCRIPTION
**Pull request by north3221**
@lanwin here is the next one so we can control the power switch for domestic hot water

### CODE REVIEW

**Comment by lanwin** [comment]
Can you please change the config name to water_heater_power? The term dhw is a little bit cryptic. 

The rest looks fine to me.

**Comment by north3221** [comment]
Hey - its funny cause I think domestic hot water is the right standard, but yeah no worries I'll update 👍

**Comment by north3221** [comment]
@lanwin done 👍

**Comment by north3221** [comment]
now tested and ready to merge

**Comment by north3221** [comment]
@lanwin you ok to merge this one now?

**Comment by lanwin** [comment]
Sorry, was on vation. Looks perfect 👯

**Pull request merged**
