### PR TITLE
Add water temperature sensor

### PR DESCRIPTION
**Pull request by Mongey**
Adds a sensor for reporting on water temperature.

### CODE REVIEW

**Comment by lanwin** [comment]
Thank you! 

I guess you use that with an heatpump right? So you create a device for the "outdoor" unit right? Witch device id does it have?

**Comment by Mongey** [comment]
yeah I've got a Heat Pump - I've got two devices setup one for indoor, one for outdoor
The indoor unit is one of these:
[](https://renewableproductswarehouse.store/products/samsung-monbloc-ht-quiet-control-kit-mim-e03en?pr_prod_strat=e5_desc&pr_rec_id=6f8e7fe79&pr_rec_pid=7664318054552&pr_ref_pid=7852952748184&pr_seq=uniform)
and the outdoor is the heat pump:
[](https://renewableproductswarehouse.store/products/samsung-monobloc-gen6-5kw-1ph-air-source-heat-pump?pr_prod_strat=e5_desc&pr_rec_id=6f8e7fe79&pr_rec_pid=7852949864600&pr_ref_pid=7852952748184&pr_seq=uniform)

I'm using the M5Stack Atom Lite linked in the readme, connected to F1/F2. The little control panel above seems to be connected to F3/F4.


I'll have a couple more PRs for other things I've gotten to work 
* outdoor temperature from the heat pump
* total power consumption Kwh
* water target temperature

I am just comparing values to what I see on the controller

**Comment by Mongey** [comment]
More like traditional heating system, it heats up water and pumps it around to radiators in each room.

There are two heating zones & domestic hot water (DHW) controlled by the system. 
The sensor implemented here is for DHW -- so water that is stored in a tank, and comes out of your tap / shower.

Upstairs and downstairs heating zones are controlled by some not-so smart [thermostat](https://www.wundagroup.com/wp-content/uploads/2019/10/E02-generic-E91-touch-screen-Stat-27-4-2018.pdf) -- I haven't been able to figure out how to determine what value tells when they are requesting heat yet.

**Comment by lanwin** [comment]
Ok then that is a lot like my geothermal heat pump (but that one is not from samsung).

Did your devices also use (indoor) 20.00.00 and (outdoor) 10.00.00 as addresses?

**Comment by Mongey** [comment]
yep
```
Configured devices: 10.00.00, 20.00.00
11:05:23	[C]	[samsung_ac:054]	Discovered devices:
11:05:23	[C]	[samsung_ac:055]	  Outdoor: 10.00.00
11:05:23	[C]	[samsung_ac:056]	  Indoor:  20.00.00
```

**Comment by lanwin** [comment]
Ok thanks. Its good to know that this all looks the same.

More pullrequests always welcome!

**Comment by mbo18** [comment]
Read me and example.yaml should be updated with this

**Comment by Foxhill67** [comment]
> yeah I've got a Heat Pump - I've got two devices setup one for indoor, one for outdoor The indoor unit is one of these: [](https://renewableproductswarehouse.store/products/samsung-monbloc-ht-quiet-control-kit-mim-e03en?pr_prod_strat=e5_desc&pr_rec_id=6f8e7fe79&pr_rec_pid=7664318054552&pr_ref_pid=7852952748184&pr_seq=uniform) and the outdoor is the heat pump: [](https://renewableproductswarehouse.store/products/samsung-monobloc-gen6-5kw-1ph-air-source-heat-pump?pr_prod_strat=e5_desc&pr_rec_id=6f8e7fe79&pr_rec_pid=7852949864600&pr_ref_pid=7852952748184&pr_seq=uniform)
> 
> I'm using the M5Stack Atom Lite linked in the readme, connected to F1/F2. The little control panel above seems to be connected to F3/F4.
> 
> I'll have a couple more PRs for other things I've gotten to work
> 
> * outdoor temperature from the heat pump
> * total power consumption Kwh
> * water target temperature
> 
> I am just comparing values to what I see on the controller

hi, may be this list helps to figure out what the codes represent: https://wiki.myehs.eu/wiki/NASA_Protocol#Message_Numbers

**Comment by Mongey** [comment]
> > yeah I've got a Heat Pump - I've got two devices setup one for indoor, one for outdoor The indoor unit is one of these: [](https://renewableproductswarehouse.store/products/samsung-monbloc-ht-quiet-control-kit-mim-e03en?pr_prod_strat=e5_desc&pr_rec_id=6f8e7fe79&pr_rec_pid=7664318054552&pr_ref_pid=7852952748184&pr_seq=uniform) and the outdoor is the heat pump: [](https://renewableproductswarehouse.store/products/samsung-monobloc-gen6-5kw-1ph-air-source-heat-pump?pr_prod_strat=e5_desc&pr_rec_id=6f8e7fe79&pr_rec_pid=7852949864600&pr_ref_pid=7852952748184&pr_seq=uniform)
> 
> > 
> 
> > I'm using the M5Stack Atom Lite linked in the readme, connected to F1/F2. The little control panel above seems to be connected to F3/F4.
> 
> > 
> 
> > I'll have a couple more PRs for other things I've gotten to work
> 
> > 
> 
> > * outdoor temperature from the heat pump
> 
> > * total power consumption Kwh
> 
> > * water target temperature
> 
> > 
> 
> > I am just comparing values to what I see on the controller
> 
> 
> 
> hi, may be this list helps to figure out what the codes represent: https://wiki.myehs.eu/wiki/NASA_Protocol#Message_Numbers 


Thanks @Foxhill67!

**Pull request merged**
