### PR TITLE
Dhw target temp 

### PR DESCRIPTION
**Pull request by north3221**
@lanwin I picked this up and I think it closes pr/#95

I rebased it to main, updated a few bits and incorporated your comments on the pr

I have tested it and it works with my heatpump. 

The only piece was I wasn't 100% sure where to mark the non-nasa not supported to I put a TODO in the non-nasa code and added to the example.yaml under not supported

Let me know any feedback and if happy with the PR merge it and I'll start adding some more things for the heatpump

### CODE REVIEW

**Comment by lanwin** [comment]
Looks good so far, but can you please check the indents (look at the file changes in github).

**Comment by north3221** [comment]
Great thanks. Yeah I did notice that but it looked ok in my editor, let me take a proper look and get that fixed 👍

**Comment by north3221** [comment]
@lanwin think I've sorted it, let me know if you spot anything else

**Comment by north3221** [comment]
@lanwin actually now its fully fixed. My editor was using tabs, not spaces. Schoolboy error, sorry

Have replaced them all and fixed my editor 😄

**Comment by north3221** [comment]
ok found a couple more

**Comment by lanwin** [comment]
No problem :D

**Comment by lanwin** [comment]
And thank you for your help!

**Comment by north3221** [comment]
Thanks Steve. More inbound :-)

**Pull request merged**
