### PR TITLE
Inverter power and thermal power requirement decoded

### PR DESCRIPTION
**Pull request by matthias882**
I had a few minutes ans so I extended the non-nasa-code to decode the F3-command

there we have now:
- the inverter max frequency
- the total power requirement for the outdoor unit
- the DC-current for the inverter of the OU
- the DC-voltage for the inverter of the OU
- the power-consupmtion for the inverter of the OU

with "debug_log_messages: true" enabled the values are shown correctly, no idea how to modify the code to get them to esphome. Thats your turn steve ;)

### CODE REVIEW

**Review by lanwin — CHANGES_REQUESTED** [review]
Thank you very much!

Could you please add the unit to the property names. This helps when they are used on the other side.

It would also help when you could add a comment to the property what the value actually means. In example I am not sure what total_capacity_requirement really is.

**Comment by matthias882** [comment]
I added some comments to the values.
The total_capacity_requirement ist the sum of the required heating or cooling demands of all indoor-units. For example if I start one indoor-unit whith heating capacity of 3500W to full power heating, the value is 3500. 2 of them in full power heating mode and the value is 7000. If there is less power required to reach the selected temperature then the sum-value is smaller.

**Comment by TCB13** [comment]
@matthias882 thank you for providing this and the other fixes.

**Comment by lanwin** [comment]
Regarding the property names. What I mean is `inverter_total_capacity_requirement` -> `inverter_total_capacity_requirement_w`

**Comment by matthias882** [comment]
Ok, next try ;)

**Comment by lanwin** [comment]
Wonderfull...thank you!

**Pull request merged**
